### ISSUE TITLE
Unable to register for account

### ISSUE THREAD

**Issue by helwoods** [NERC-CEH/bloominalgae-app#12]
When you try to register for an irecord account and hit 'create' the e-mail box is underlined in red with the message invalid. I tried a number of different e-mail accounts all with the same result.

**Comment by kazlauskis** [comment]
Hi, could you please give me an example of an email you are trying to enter?

**Comment by helwoods** [comment]
I have just tried again and I managed to register a new e-mail address fine, it might have been linked to the firewall issue here at CEH Edinburgh.
