### ISSUE TITLE
Login remains for BRC pages after app logout

### ISSUE THREAD

**Issue by ScienceAndMaps** [NERC-CEH/bloominalgae-app#16]
There's an error if you follow these steps:

1. Login to the app, then view one of your submitted records on iRecord (via the app 'View on iRecord' button)
2. Logout of the app
3. Go to one of the records and view on iRecord again and you will still be logged in on the iRecord webpage.

This means that if more than one person is using the app, they could potentially see someone else's iRecord account details. If possible, it would be good that logging out of the app also logs out of the iRecord website.

**Comment by kazlauskis** [comment]
Hi @philor-CEH, unfortunately, this is something I can't do at the moment. The app and website are two different systems that are not linked in terms of sharing login sessions. The website is opened on your browser, so when you click on that link in the app you are redirected to the browser where you have to login once more.
