### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by ScienceAndMaps** [NERC-CEH/bloominalgae-app#2]
You can't submit a record without a location name, which needs to be typed manually. This seems unnecessary when a GPS location has been found.

Would it be possible to submit a location via lat, long? Lots of people won't know their grid reference despite having a GPS.

**Comment by kazlauskis** [comment]
Sure, will remove the requirement to send the name.

**Comment by LaurenceCarvalho** [comment]
I think location name should be kept as an optional field but agree isn't necessary if they can get a GPS reading, but sometimes people wander away before recording, so it may be useful to give a clear description e.g. "Loch Leven harbour" - I noted my record from Loch Leven appeared to be in the car park next to the harbour - so text can help sort out idiots like me who wander back to the car whilst recording.

**Comment by ScienceAndMaps** [comment]
yeah, happy with it being optional
