### ISSUE TITLE
Submitting a record as a guest?

### ISSUE THREAD

**Issue by ScienceAndMaps** [NERC-CEH/bloominalgae-app#24]
Is there any way to send records to iRecord without an account? (say, an anonymous user that is logged in automatically?). We're not sure if making people sign up for  iRecord will be some casual users off the app, who might be happy to submit a record and never hear about it again. Is this something that can be done, or does iRecord not allow it?

**Comment by kazlauskis** [comment]
It comes down how critical this is. I would prefer to add it in the next (version 2) app release. This requirement complicates the app submission process and unless this is necessary for the v1 of the app then I would leave it for the v2.

**Comment by kazlauskis** [comment]
For the v2 of the app we will require everyone to have a registered account and be logged in before uploading any data.
