### ISSUE TITLE
queens hall edinburgh

### ISSUE THREAD

**Issue by LaurenceCarvalho** [NERC-CEH/bloominalgae-app#27]

**Comment by kazlauskis** [comment]
Sorry, what's this? 🙂

**Comment by LaurenceCarvalho** [comment]
Sorry – that was me doing a google search for the Queen’s Hall!  I typed it into github webpage accidentally – I thought I’d deleted it!

Laurence

**Comment by kazlauskis** [comment]
Ah, no worries!
