### ISSUE TITLE
Record deleted after returning from send

### ISSUE THREAD

**Issue by ScienceAndMaps** [NERC-CEH/bloominalgae-app#3]
If you go to send a record, then go back without doing anything, all your information disappears

**Comment by ScienceAndMaps** [comment]
NB when this happens, the record is accessible via the user button in the top menu, but it should display by default if it hasn't yet been sent

**Comment by kazlauskis** [comment]
Yes, it should inform the user of the sending process better. At the moment on submit it sends a record and creates a new draft that the user see's as an empty record again.
