### ISSUE TITLE
Text overlaps date on map items without a photo.

### ISSUE THREAD

**Issue by yemling** [NERC-CEH/bloominalgae-app#32]
Verified records don't overlap, but I think any for record that doesn't have images, the box isn't wide enough and the rejected [or whatever] text overlaps the date.
Tested in both portrait and landscape, on Android.

**Comment by kazlauskis** [comment]
Hi, could you please provide a screenshot of this as I couldn't reproduce this issue. What are the device model and Android version in use? Cheers

**Comment by yemling** [comment]
[Image]

Samsung S10, should be the latest version.
Gemma

________________________________
