### ISSUE TITLE
Record pending stuck and won't upload (and no possibility to delete)

### ISSUE THREAD

**Issue by LaurenceCarvalho** [NERC-CEH/bloominalgae-app#39]
I've had a test record pending for several days now - it seems to be stuck in my "pending" folder - I've sent others since and they have gone, but this one is just stuck and I cannot delete it.

Can we add an option for a user to delete a pending record for this sort of problem?

Laurence

**Comment by kazlauskis** [comment]
@LaurenceCarvalho I don't see anything in our error logs and so I would need some more information to fix this issue. What do you see when you try to delete it? What device and platform/version are you using? If you could try this again and then give me the exact time you've tried this then I can double check our error logs for anything suspicious.

I think this might be early-testing related as we were changing things more in that period when you were testing. My suggestion would be to reset the app in the App Settings for now and keep this ticket open to see if other users discover something similar.

**Comment by LaurenceCarvalho** [comment]
Hi Karolis

Just sorting through your emails now

I reset the app and that cleared the pending record – so that’s sorted ☺

I think I still have the issue that my records turn to “Plausible” status after 20-30 mins after uploading and then change status (to incorrect) when someone actually verifies them – this happened yesterday

Laurence
