### ISSUE TITLE
Main page title

### ISSUE THREAD

**Issue by ScienceAndMaps** [NERC-CEH/bloominalgae-app#4]
On the main page, the title is a bit bold and takes up a lot of space. I've attached a potential design change that uses the logo and a less-bold font. This allows more room on smaller phones for the sections below.
![main_page](https://cloud.githubusercontent.com/assets/26765140/24451876/82745930-1478-11e7-8dcf-29ca878fd8f2.jpg)

**Comment by kazlauskis** [comment]
What font did you use for that?

**Comment by LaurenceCarvalho** [comment]
I agree with Phil.  Please can you include the app logo and a simpler text to the main page. I like the look of Phil's suggestion.

**Comment by kazlauskis** [comment]
Sure, just let me know what font you have used for it, or even better send me an svg/eps/il formatted image.

**Comment by ScienceAndMaps** [comment]
Hi Karolis, it was a font called Anivers, I've attached it here.

[anivers-reg.zip](https://github.com/NERC-CEH/bloominalgae-app/files/885685/anivers-reg.zip)

**Comment by kazlauskis** [comment]
Love the font. Done it now, thanks!

**Comment by ScienceAndMaps** [comment]
Hi Karolis - for consistency, could we use the same font on the loading screen, without the border? (I can clarify if that's not clear)

**Comment by kazlauskis** [comment]
Will do that, thanks.
