### ISSUE TITLE
Adding french translator to the acknowledgements

### ISSUE THREAD

**Issue by LaurenceCarvalho** [NERC-CEH/bloominalgae-app#42]
Please add Annick Wilmotte to the acknowledgments for doing the French translation:
[I'm not sure if this goes in all language versions or just if you select French? It maybe best if the latter is an option (i.e. just in French version) otherwise the acknowledgement list will potentially increase too long if more languages become available in the future.

Here's Annick's suggested text: "Traduction en français: Annick Wilmotte (Université de Liège)"

Other language options:
 'French translation/Traduction en français/Franse vertaling (depending on language): Annick Wilmotte (Université de Liège)

**Comment by Vilius-Stankaitis** [comment]
It might be better to create a separate translators list/segment when more languages are added.

![Screenshot 2021-08-02 at 12.45.10.png](https://zube.io/files/nerc-ceh/924d7e4776edb4bccc7b576b89ce3e03-screenshot-2021-08-02-at-12-45-10.png)
