### ISSUE TITLE
Update Privacy policy

### ISSUE THREAD

**Issue by CamillaHagman** [NERC-CEH/bloominalgae-app#47]
Privacy policy should be updated to "www.irecord.org.uk/privacy-notice"

**Comment by kazlauskis** [comment]
Do you want to show an actual link instead of the "Privacy policy"? If it is an actual link then it wouldn't be tappable, ie. it wouldn't open the browser page.

**Comment by CamillaHagman** [comment]
Hi,

No, we don’t want a link instead of «Privacy Policy”, just to update the actual link behind. Laurence went through them in my translation document and found that they are not correct anymore. The correct link is what I wrote in GitHub. Might be that the translation document was wrong, but good if you could check it out. We decided to keep the English version of the privacy policy and just link to the existing page – not make a new one in Norwegian.


Vennlig hilsen | Best regards,
Camilla H. Corneliussen Hagman
Forsker, PhD | Researcher, PhD
Seksjon for ferskvannsøkologi | Section for Freshwater Ecology
----------------------------------------------------------------------------------------
Norsk Institutt for Vannforskning (NIVA)
Norwegian Institute for Water Research
Gaustadalléen 21, 0349 Oslo, Norway
Mob.: (+47) 906 15 679 | ***@***.******@***.***> | www.niva.no<http://www.niva.no/>
----------------------------------------------------------------------------------------
