### ISSUE TITLE
Language choice

### ISSUE THREAD

**Issue by CamillaHagman** [NERC-CEH/bloominalgae-app#51]
Hi, as we have discussed earlier, we would need to have the options of first choosing country (Norway), and then language. As some people in Norway may want to use English (or Dutch) in stead of Norwegian language, but still need to chose the region other than UK.

**Comment by kazlauskis** [comment]
Sure, I'll add the option for the country too.

**Comment by kazlauskis** [comment]
I've added the country option now. The app language is going to default to whatever the device language is. So if you have selected Norwegian for as you primary device language then the app will show country choices in Norwegian too. You can also select a different country or language in the app settings.


<img width="373" alt="Screenshot 2022-05-27 at 09 34 05" src="https://user-images.githubusercontent.com/7383162/170644274-23ee14fe-a674-4f7b-b435-3e8e64d73aa3.png">

<img width="375" alt="Screenshot 2022-05-27 at 09 30 37" src="https://user-images.githubusercontent.com/7383162/170644266-108fb88a-9f08-4afe-be38-15de13745eac.png">

<img width="373" alt="Screenshot 2022-05-27 at 09 35 12" src="https://user-images.githubusercontent.com/7383162/170644422-f6faba89-3a07-421d-a15d-d9921bf6ae62.png">

**Comment by CamillaHagman** [comment]
Hi,

That looks good, thank you! It doesn’t show up like that in my demo-app, but maybe the link from before needs to be updated with country? So I trust it’s fine 😊
We noticed that the links for NIVA and Folkehelseinstituttet (FHI) under further actions (videre handling) are not working properly, but the Veterinærinstiuttet link is ok. Should I make another issue on that?


Vennlig hilsen | Best regards,
Camilla H. Corneliussen Hagman
Forsker, PhD | Researcher, PhD
Seksjon for ferskvannsøkologi | Section for Freshwater Ecology
----------------------------------------------------------------------------------------
Norsk Institutt for Vannforskning (NIVA)
Norwegian Institute for Water Research
Gaustadalléen 21, 0349 Oslo, Norway
Mob.: (+47) 906 15 679 | ***@***.******@***.***> | www.niva.no<http://www.niva.no/>
----------------------------------------------------------------------------------------

**Comment by kazlauskis** [comment]
The demo app takes about 30mins to refresh with new changes, so I suggest to check it then 🙂 I am not sure why the links aren't working for you, can you please check these in the demo app again once it is updated?

**Comment by CamillaHagman** [comment]
Hi,

I checked the links again now, and it’s only Veterinærinstituttet that is working properly. It is both under Further actions/Videre tiltak and Health risks/Helsefarer, and both are working. Under Further actions/Videre tiltak the links to NIVA and Folkehelseinstituttet are not working properly.

They should be
NIVA - https://www.niva.no/forskning/ferskvannsokologi/cyanobakterier
Folkehelseinstituttet – https://www.fhi.no



Vennlig hilsen | Best regards,
Camilla H. Corneliussen Hagman
Forsker, PhD | Researcher, PhD
Seksjon for ferskvannsøkologi | Section for Freshwater Ecology
----------------------------------------------------------------------------------------
Norsk Institutt for Vannforskning (NIVA)
Norwegian Institute for Water Research
Gaustadalléen 21, 0349 Oslo, Norway
Mob.: (+47) 906 15 679 | ***@***.******@***.***> | www.niva.no<http://www.niva.no/>
----------------------------------------------------------------------------------------

**Comment by kazlauskis** [comment]
Ah, I see what you mean now. These two websites have a limitation from loading in iFrames which this demo app currently is. In other words, in the real app on a device it will work fine.

**Comment by CamillaHagman** [comment]
Ok, then everything should be ok 😊 Thanks!


Vennlig hilsen | Best regards,
Camilla H. Corneliussen Hagman
Forsker, PhD | Researcher, PhD
Seksjon for ferskvannsøkologi | Section for Freshwater Ecology
----------------------------------------------------------------------------------------
Norsk Institutt for Vannforskning (NIVA)
Norwegian Institute for Water Research
Gaustadalléen 21, 0349 Oslo, Norway
Mob.: (+47) 906 15 679 | ***@***.******@***.***> | www.niva.no<http://www.niva.no/>
----------------------------------------------------------------------------------------

**Comment by kazlauskis** [comment]
Excellent, should we release it for Beta testing now then?

**Comment by CamillaHagman** [comment]
Yes, it’s ready for Beta testing 😊

Thanks for all your help!!


Vennlig hilsen | Best regards,
Camilla H. Corneliussen Hagman
Forsker, PhD | Researcher, PhD
Seksjon for ferskvannsøkologi | Section for Freshwater Ecology
----------------------------------------------------------------------------------------
Norsk Institutt for Vannforskning (NIVA)
Norwegian Institute for Water Research
Gaustadalléen 21, 0349 Oslo, Norway
Mob.: (+47) 906 15 679 | ***@***.******@***.***> | www.niva.no<http://www.niva.no/>
----------------------------------------------------------------------------------------

**Comment by kazlauskis** [comment]
OK, I'll let you know when it's ready to install, thanks!

**Comment by CamillaHagman** [comment]
Sorry, country option showed up when I tried the demo-app again now 😉


Vennlig hilsen | Best regards,
Camilla H. Corneliussen Hagman
Forsker, PhD | Researcher, PhD
Seksjon for ferskvannsøkologi | Section for Freshwater Ecology
----------------------------------------------------------------------------------------
Norsk Institutt for Vannforskning (NIVA)
Norwegian Institute for Water Research
Gaustadalléen 21, 0349 Oslo, Norway
Mob.: (+47) 906 15 679 | ***@***.******@***.***> | www.niva.no<http://www.niva.no/>
----------------------------------------------------------------------------------------

**Comment by kazlauskis** [comment]
> Sorry, country option showed up when I tried the demo-app again now 😉

Are you saying that you've opened up the web demo in the past, selected the country and now opened the demo again and the countries list has appeared once more, is that right? The countries selection will appear again if you open the demo after a long period or on another browser. The web demo state isn't as persistent as it is on mobile devices.
