### ISSUE TITLE
Automatic language selection not obvious

### ISSUE THREAD

**Issue by LaurenceCarvalho-NIVA** [NERC-CEH/bloominalgae-app#52]
Hi Karolis. I just downloaded the new test flight version and selected "Norway" as my country and then it immediatley went to the app in English.  I know you said it would default to the phone language but I think we need a pop-up message saying:

The language will default to the language of your phone settings. If you want to change the language go to "settings" in the Bloomin Algae app menu and select "language"

We will need translation so this pop-up though!

**Comment by CamillaHagman** [comment]
Norwegian translation:
Appen vil automatisk velge språket som er valgt i dine telefoninnstillinger. Hvis du ønsker å endre språk, gå til "Innstillinger" i app-menyen til Bloomin' Algae og velg "Språk"
