### ISSUE TITLE
No indication that sighting has been submitted

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/bloominalgae-app#9]
After submitting an observation, the app returns a page to add in details for the next occurrence - it is not obvious to the user that submission has been successful.  Possible solutions.
1. Add a 'success' message box
2. Return to a list of submitted sightings (i.e. like the iRecord App)
3. Add a 'Records' link from the App info page (i.e. like the Asian Hornet Watch App)

**Comment by kazlauskis** [comment]
Yes, I will do that. This links to #3

**Comment by ScienceAndMaps** [comment]
I think David's idea #2 would work well, as this will help users discover this records page as well. It would be good for this page to have a title ('My Records'?) and potentially a way to make it clear they can get back to this page by clicking the user icon at the top
